# Generated by Django 5.2.5 on 2025-08-26 16:49

from django.db import migrations

def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Topic = apps.get_model('core', 'Topic')
    Article = apps.get_model('core', 'Article')

    # Create a user
    user, created = User.objects.get_or_create(
        username='admin',
        defaults={
            'is_staff': True,
            'is_superuser': True,
            'email': 'admin@example.com'
        }
    )

    # Create topics
    topic1, created = Topic.objects.get_or_create(title='Introduction to Computers', slug='intro-to-computers')
    topic2, created = Topic.objects.get_or_create(title='Programming with Python', slug='python-programming')

    # Create articles
    Article.objects.get_or_create(
        topic=topic1,
        title='What is a Computer?',
        slug='what-is-a-computer',
        defaults={'content': 'This is an article about computers.', 'author': user}
    )
    Article.objects.get_or_create(
        topic=topic2,
        title='Your First Python Program',
        slug='first-python-program',
        defaults={'content': 'This is an article about Python programming.', 'author': user}
    )

def delete_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Topic = apps.get_model('core', 'Topic')
    Article = apps.get_model('core', 'Article')
    User.objects.filter(username='admin').delete()
    Topic.objects.filter(slug__in=['intro-to-computers', 'python-programming']).delete()
    Article.objects.filter(slug__in=['what-is-a-computer', 'first-python-program']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_code=delete_initial_data),
    ]
